// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingMaster.ProdutosAPI.Data;

#nullable disable

namespace ShoppingMaster.ProdutosAPI.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240909163942_adicionando_produtos_ficticios")]
    partial class adicionando_produtos_ficticios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShoppingMaster.ProdutosAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Category_Name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Price");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("Image_URL");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 6L,
                            Category = "Tablets",
                            Description = "Tablet muito potente",
                            Name = "Tablet APi12",
                            Price = 3200.12m,
                            Url = "https://via.placeholder.com/150?text=Tablet+APi12"
                        },
                        new
                        {
                            Id = 7L,
                            Category = "Roupas",
                            Description = "Camisa de algodão de alta qualidade",
                            Name = "Camisa Casual Azul",
                            Price = 89.99m,
                            Url = "https://via.placeholder.com/150?text=Camisa+Casual+Azul"
                        },
                        new
                        {
                            Id = 8L,
                            Category = "Roupas",
                            Description = "Calça jeans com corte moderno",
                            Name = "Calça Jeans Slim",
                            Price = 129.9m,
                            Url = "https://via.placeholder.com/150?text=Calca+Jeans+Slim"
                        },
                        new
                        {
                            Id = 9L,
                            Category = "Celulares",
                            Description = "Smartphone com 8GB de RAM e câmera de 64MP",
                            Name = "Smartphone X1000",
                            Price = 2999.99m,
                            Url = "https://via.placeholder.com/150?text=Smartphone+X1000"
                        },
                        new
                        {
                            Id = 10L,
                            Category = "Celulares",
                            Description = "Smartphone com 5G e tela AMOLED",
                            Name = "Smartphone ZPro",
                            Price = 3499.49m,
                            Url = "https://via.placeholder.com/150?text=Smartphone+ZPro"
                        },
                        new
                        {
                            Id = 11L,
                            Category = "Cabos",
                            Description = "Cabo USB-C de 1 metro, rápido e durável",
                            Name = "Cabo USB-C Rápido",
                            Price = 29.99m,
                            Url = "https://via.placeholder.com/150?text=Cabo+USB-C"
                        },
                        new
                        {
                            Id = 12L,
                            Category = "Cabos",
                            Description = "Cabo HDMI 4K de 2 metros",
                            Name = "Cabo HDMI 4K",
                            Price = 49.99m,
                            Url = "https://via.placeholder.com/150?text=Cabo+HDMI+4K"
                        },
                        new
                        {
                            Id = 13L,
                            Category = "Carros",
                            Description = "Sedan esportivo com motor turbo",
                            Name = "Sedan Turbo GT",
                            Price = 49999m,
                            Url = "https://via.placeholder.com/150?text=Sedan+Turbo+GT"
                        },
                        new
                        {
                            Id = 14L,
                            Category = "Carros",
                            Description = "SUV com tração integral e interior de couro",
                            Name = "SUV Luxury X",
                            Price = 69999m,
                            Url = "https://via.placeholder.com/150?text=SUV+Luxury+X"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
